scvelo/preprocessing/utils.py
A cleaner and shorter implementation of the cleanup function.
=> Improved cleanup function

scvelo/get_version.py
=> Updated get_version

scvelo/plotting/scatter.py
We could further add the parameters as arguments to scatter:
scale_param : width of the density plots
alpha_param : alpha of the plot fill
color of the density plots
=> Density option for scatter plots

scvelo/tools/rank_velocity_genes.py
Gets the 1-Dimensional base array instead of matrix. It aims to fix issue #98
=> Fix Issue #98

scvelo/tools/rank_velocity_genes.py
Apparently also this line needs to be changed to fix issue #98
=> Final fix #98

scvelo/tools/utils.py, scvelo/tools/velocity_graph.py
This PR introduces a `mode_neighbors` which allows one to compute the KNN graph either on the `distances` or on the `connectivities`, see #113
=> Mode neighbors

scvelo/plotting/paga.py
Hey @VolkerBergen ,
this PR allows user to specify node colors. If `None`, it's just as before. Marius and I want to use it for pie charts, see this issue https://github.com/theislab/cellrank/issues/134.
=> Add node colors to paga

scvelo/plotting/paga.py
Hi @VolkerBergen ,
I've managed to fix the node sizes/arrow when plotting the pie charts in `scv.pl.paga`, as mentioned in https://github.com/theislab/cellrank/issues/125. The idea is simple: just get the bounding boxes around the markers and use correct transformations to get the pie sizes.
Here's a code to reproduce the plots below:
```python
import scvelo as scv
import numpy as np
np.random.seed(42)
adata = scv.datasets.toy_data(100)
scv.pp.neighbors(adata)
scv.tl.velocity_graph(adata)
scv.tl.paga(adata)
x = {i: {"#ff0000": 0.5} for i in range(12)}
scv.pl.paga(adata, node_size_scale=3, dpi=100, node_colors=x)
```
Before:
After
To validate that the sizes are correct, I set `linewidths=1, c='g'` in https://github.com/theislab/scvelo/blob/master/scvelo/plotting/paga.py#L638 and it almost …
=> Fix paga_pie node_size

docs/source/_ext/edit_on_github.py, docs/source/conf.py
Hi @VolkerBergen ,
Marius pointed me to this issue https://github.com/theislab/scvelo/issues/209.
I think this should work. Could you please test it?
=> Add custom links for notebooks

scvelo/plotting/pseudotime.py, scvelo/plotting/simulation.py, scvelo/tools/dynamical_model.py, scvelo/tools/dynamical_model_utils.py, scvelo/tools/dynamical_model_utils_deprecated.py, scvelo/tools/rank_velocity_genes.py, scvelo/tools/velocity_pseudotime.py
* `np.where` is replaced by the pandas index method `get_loc` wherever possible.
Closes #274.
=> Feat / Remove np.where wherever possible

scvelo/preprocessing/neighbors.py
* The number of components is ensured to be smaller than both the number of variables as well as observations
Closes #336.
=> Fix definition of number of principal components

scvelo/tools/dynamical_model_utils.py
* Vectorization of [this](https://github.com/theislab/scvelo/blob/d86753457da72c4766d1b40a60948f8cfa3559a2/scvelo/tools/dynamical_model_utils.py#L198) for loop
Closes #332.
=> Vectorize for loop

scvelo/tools/terminal_states.py, scvelo/tools/utils.py
* Add argument `modality` to `verify_roots`, `terminal_states` and `get_plasticity_score`.
Closes #339.
=> Allow using arbitrary layer for terminal state calculation

scvelo/tools/dynamical_model.py
* `n_jobs` can now be given as an arbitrary integer.
* The function `get_n_jobs` is added updates the number of jobs `n_jobs` to the expected format.
=> Fix definition of `n_jobs`

.github/ISSUE_TEMPLATE/general_question.md, README.rst, docs/source/index.rst
* Rephrases the _Support_ section in `README.rst` and `docs/source/index.rst` to clarify when to open issues and when to use GitHub discussions.
* Removes issue template for question.
=> Move questions to GitHub discussions

.github/workflows/ci.yml
* Refactors `linting` stage of CI to use pre-commit hooks.
Closes #375.
=> Update linting stage in CI

CONTRIBUTING.rst, requirements-dev.txt, setup.py
* Packages used in the codebase but missing in `requirements-dev.txt` are added to the file.
* The `dev` installation option in `setup.py` is refactored to collect the required packages from `requirements-dev.txt`.
* `CONTRIBUTING.md` is added as a contribution guide.
Closes #382
=> Improve developer installation and guide

scvelo/tools/velocity_graph.py
* Computation of cosine similarity is parallelised
closes #391
=> Parallelize cosine similarity computation

scvelo/plotting/utils.py
* Pandas `is_categorical` is replaced by `is_categorical_dtype`.
Closes #401
=> Replace pandas is_categorical

CONTRIBUTING.rst, docs/source/installation.rst
* Update instructions for developer installation.
Closes #450.
=> Update developer installation instructions

requirements.txt
* Unpins upper bound on numba.
Closes #480.
=> Unpin upper bound on numba

scvelo/plotting/velocity_embedding_stream.py
Adding new streamplot arguments:
- arrow_size: Scaling factor for the arrow size, addressing https://github.com/theislab/scvelo/issues/486
- arrow_style: Arrow style specification, '-|>' or '->'.
- max_length: Maximum length of streamline in axes coordinates.
- integration_direction: Integration in 'forward', 'backward' or 'both' directions.
=> Extend `pl.velocity_embedding_stream` with new arguments

docs/source/index.rst, docs/source/perspectives.rst, docs/source/perspectives/index.rst
* Creates index page for perspectives.
=> Create perspectives landing page

scvelo/core/tests/test_anndata.py
* Adds test class for `scvelo/core/_anndata.py::clean_obs_names`.
Related to #226
=> Add TestCleanObsNames

tests/core/test_anndata.py
* Adds test class `TestGetSize` to test `scvelo/core/_anndata.py::get_size`.
Closes #555.
=> Add `TestGetSize`

scvelo/__init__.py, scvelo/pl.py, scvelo/pp.py, scvelo/tl.py
* Deletes `pl.py`, `pp.py`, `tl.py`.
* Refactors and update `scvelo/__init__.py` to use `scvelo.pl`, `scvelo.pp`, `scvelo.tl` out of the box.
Closes #559.
=> Update __init__.py and delete pl.py, pp.py, tl.py

tests/core/test_anndata.py
* Adds `TestVarDf` to unit test `scvelo.core._anndata.py::var_df`.
Closes #582.
=> Add `TestVarDf`

tests/core/test_anndata.py
* Adds assertion statement to `TestObsDf` to verify the used index.
Closes #584.
=> Add assertion statement to `TestObsDf`

tests/core/test_anndata.py
* Adds `TestShowProportions` unit testing `scvelo.core._anndata.py::show_proportions`.
Closes #588.
=> Add `TestShowProportions`

tests/core/test_anndata.py
* Adds test class `TestSetInitialSize`.
Closes #590.
=> Unit tests for `set_initial_size`

tests/core/test_anndata.py
* Add test class to unit test `scvelo/core/_anndata.py::merge`.
Closes #610.
=> Add `TestMerge`

tests/core/test_base.py
* Reset `min_varm` and `max_varm` if `varm_keys` is specified.
=> Fix AnnData strategy

tests/core/test_anndata.py
* Fixes comparison of number of layers after cleanup.
Closes #621.
=> Fix `TestCleanup`

tests/core/test_anndata.py
* Unit tests for `scvelo/core/_anndata.py::get_df`.
Closes #623.
=> Add `TestGetDf`

scvelo/datasets/_datasets.py
* Sort functions alphabetically
* Add TODO
Related to #636.
=> Cleanup `datasets/_datasets.py`

scvelo/datasets/_datasets.py
* Specify correct `scvelo` version in `DeprecationWarning`
Closes #639.
=> Fix `DeprecationWarning`

scvelo/datasets/_datasets.py
* Allow saving/reading datasets to/from custom paths.
Closes #641.
=> Add `file_path` as argument

docs/source/release_notes.rst
@WeilerP feel free to add, if anything is missing. 
Closes #628.
=> Add release notes for 0.2.4

scvelo/datasets/__init__.py
* Adds in `scvelo=0.2.4` newly added datasets to `datasets/__init__.py`.
Closes #676.
=> Add new datasets to `datasets/__init__.py`

scvelo/preprocessing/neighbors.py
* Splits content of `neighbors` function into several private functions.
* Fixes a typo in the docstrings of `neighbors`.
* Type annotation for arguments of `neighbors`
Closes #794.
=> Refactor `neighbors`

.github/workflows/ci.yml, requirements-dev.txt
* Adds `pytest-cov` to `requirements.txt`.
* Dependencies are now installed using `pip install -e '.[dev]'` in the `test` job.
Closes #802.
=> Refactor testing in CI

scvelo/tools/dynamical_model.py
* Prevents `scaling` to be fitted/optimized when `fit_scaling=False` is specified.
Closes #849.
=> Fix inference with `fit_scaling=False`

.pre-commit-config.yaml, requirements-dev.txt, scvelo/core/_linear_models.py, scvelo/plotting/utils.py, scvelo/plotting/velocity.py, scvelo/plotting/velocity_embedding_grid.py, scvelo/plotting/velocity_embedding_stream.py, scvelo/preprocessing/utils.py, scvelo/tools/dynamical_model_utils.py, scvelo/tools/optimization.py, scvelo/tools/rank_velocity_genes.py, scvelo/tools/transition_matrix.py, scvelo/tools/utils.py, scvelo/tools/velocity.py, scvelo/tools/velocity_graph.py, tests/datasets/test_simulate.py, tests/preprocessing/test_moments.py, tests/preprocessing/test_neighbors.py
* Fixes incompatible versions between `black` and `pre-commit`.
* Updates to latest versions of `pre-commit`, `isort` and `black`
Closes #854.
=> Update `pre-commit` setup

scvelo/datasets/_datasets.py
* Adds argument `file_path` to datasets added in `scvelo=0.2.4.`.
Closes #852.
=> Add argument `file_path` for datasets added in `scvelo=0.2.4`

scvelo/plotting/velocity_embedding_stream.py
=> Fix missing write_key for embedding stream plot.

scvelo/core/_anndata.py
* Fixes how Pandas` precision option is set.
Closes #906.
=> Fix Pandas display precision

CONTRIBUTING.rst, docs/requirements.txt, docs/source/conf.py, docs/source/index.rst, scvelo/datasets/_datasets.py, scvelo/tools/velocity_embedding.py
* Update description of branch structure
* Pin `Jinja` version to `<3.1`
* Update `add_stylesheet` with `add_css_file`
* Fix typo in `index.rst`
* Fix link to bone marrow datasets
* Fix `velocity_embedding` docs
Closes #747, #928.
=> Fix docstring issues

docs/source/_key_contributors.rst, docs/source/index.rst
* Add section with key contributors.
Closes #352.
=> Add key contributors section

tests/core/test_linear_models.py
* Updates unit tests `TestLinearRegression::test_perfect_fit` and `TestLinearRegression::test_perfect_fit_2d` to resolve numerical issues causing tests to fail.
Closes #939.
=> Fix linear regression unit tests

requirements.txt
* Pin `scikit-learn` to prior to `1.2.0`.
Closes #967.
=> Pin `scikit-learn` to prior ro 1.2.0

scvelo/core/_anndata.py
-   Fixes case where variable `id_length` is referenced before assignment
Closes #983.
=> Fix `core/_anndata.py:merge`

pyproject.toml, scvelo/preprocessing/moments.py, tests/preprocessing/test_moments.py
- Removes function `magic_impute`
- Removes `magic-impute` from packages
Closes #1078.
=> Remove `magic_impute`

pyproject.toml
-   Update `pyproject.toml` to filter warnings to increase readability of test logs.
Closes #1082.
=> Filter test warnings

docs/source/installation.rst, pyproject.toml, scvelo/tools/paga.py
-  Updates package specification from `python-igraph` to `igraph`
Closes #1099.
=> Update from `python-igraph` to `igraph`

scvelo/inference/__init__.py, scvelo/inference/_metabolic_labeling.py
- Adds functions to infer kinetic rates from metabolic labeling data.
Closes #1102.
=> Add metabolic labeling inference

pyproject.toml
* Unpin scikit-learn
Closes #1197.
=> Unpin scikit-learn

docs/source/api.rst, scvelo/__init__.py, scvelo/plotting/__init__.py, scvelo/tools/__init__.py
- Remove import statements of unused Scanpy functions
- Update docs accordingly
Closes #1275.
=> Remove redundant Scanpy functions

README.md, docs/source/index.rst, docs/source/references.bib, scvelo/inference/_metabolic_labeling.py
- Update CR2 references to published paper.
Closes #1271.
=> Update CR2 reference
