theislab/scvelo

scvelo/plotting/velocity_embedding_grid.py, scvelo/tools/velocity_embedding.py
Now this is possible:
```PYTHON
gs = plt.GridSpec(1, 2, plt.figure(None, (8, 4), dpi=70))
scv.pl.velocity_embedding(adata, basis='draw_graph_fa', ax=plt.subplot(gs[0]), show=False)
scv.pl.velocity_embedding_stream(adata, basis='draw_graph_fa', ax=plt.subplot(gs[1]), show=False)
scv.pl.velocity_embedding_stream(adata, basis='draw_graph_fa', ax=plt.subplot(gs[2]), show=False)
```
Before, `scvelo.tools.quiver_autoscale` was creating a new figure that override any previous figure already set resulting in something like this:
```PYTHON
gs = plt.GridSpec(1, 3, plt.figure(None, (12, 4), dpi=70))
scv.pl.velocity_embedding(adata, basis='draw_graph_fa', ax=plt.subplot(gs[0]), show=False)
scv.pl.velocity_embedding_stream(adata, basis='draw_graph_fa', ax=plt.subplot(gs[1]), show=False) …
```
=> create new separate figure for quiver_autoscale to protect main figure

scvelo/tools/rank_velocity_genes.py
Running the current version of `scv.tl.rank_velocity_genes.rank_velocity_genes()` throws the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-57-089e06e333aa> in <module>
----> 1 np.rec.fromarrays([n for n in rankings_gene_names], dtype=[(rn, 'U50') for rn in groups])
~/miniconda3/envs/rtools/lib/python3.7/site-packages/numpy/core/records.py in fromarrays(arrayList, dtype, shape, formats, names, titles, aligned, byteorder)
616 
617     if dtype is not None:
--> 618         descr = sb.dtype(dtype)
619         _names = descr.names
620     else:
TypeError: data type not understood
```
The error arises from …
=> Recast group values as strings in dtype argument when creating np.recarrays in scv.tl.rank_velocity_genes.rank_velocity_genes()

scvelo/plotting/__init__.py, scvelo/plotting/paga.py, scvelo/tools/__init__.py, scvelo/tools/paga.py
scv.pl.paga is now the scv version of paga that (if a basis is given) projects the paga graph onto the scatter plot in the embedding.
scv.tl.paga is the scv version of paga in tools that accepts vkey as an argument.
=> Add Paga plot with vkey arguments

scvelo/datasets.py, scvelo/logging.py, scvelo/plotting/paga.py, scvelo/plotting/scatter.py, scvelo/plotting/simulation.py, scvelo/plotting/utils.py, scvelo/plotting/velocity.py, scvelo/plotting/velocity_embedding.py, scvelo/plotting/velocity_embedding_grid.py, scvelo/plotting/velocity_embedding_stream.py, scvelo/preprocessing/neighbors.py, scvelo/preprocessing/utils.py, scvelo/settings.py, scvelo/tools/dynamical_model.py, scvelo/tools/dynamical_model_utils.py, scvelo/tools/dynamical_model_utils_deprecated.py, scvelo/tools/rank_velocity_genes.py, scvelo/tools/utils.py, scvelo/tools/velocity_graph.py
Fixes #151.
Basically I searched all occurences of this regex `\wis\w(?!(not\w)?(None|np\.nan))`. Mostly for things like the *really* widespread `if mode is 'something'` or 'if number is 0' or `if show is False: return ax` (the last one is the only one that’s not wrong, just overeager).
I skipped the `is (not) True/False` ones that look right, e.g. because you did:
```py
if not thing:
if thing is True: special_case()
common_case(thing)
```
Please check all those spots anyway, I might have made an incorrect assumption somewhere.
=> Fix all comparisons wrongly done with `is`

scvelo/plotting/utils.py
Hi @VolkerBergen ,
apparently, if there's `'x'` and `'y'` in `adata.obs`, `interpret_color` does not work. Culprit: https://github.com/theislab/scvelo/blob/master/scvelo/plotting/scatter.py#L550 + https://github.com/theislab/scvelo/blob/master/scvelo/plotting/utils.py#L680
This PR fixes this.
```python3
import scvelo as scv
adata.obs['foo'] = 'bar'
adata.obs.loc[adata.obs_names[:1000], 'foo'] = 'baz'
adata.obs.loc[adata.obs_names[1000:2000], 'foo'] = np.nan
adata.obs['foo'] = adata.obs['foo'].astype('category')
adata.obs['x'] = 0
adata.obs['y'] = 0
#AnnData object with n_obs × n_vars = 3696 × 27998
scv.pl.scatter(adata, color='foo', basis='pca')
```
```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most …
```
=> Fix interpret colors

scvelo/preprocessing/neighbors.py
* Add the used representation to calculate the neighbor graph to `adata.uns["neighbors"]["params"]` in the function `neighbors`.
* Refactor the function `get_n_neighs` into a more concise and pythonic way.
Closes #271. Closes #272.
=> Fix and refactor / Neighbors

requirements.txt
* Use umap-learn version priot to `0.5`.
* Closes #329. Related to #326, #328.
=> Fix umap-learn version

scvelo/tools/dynamical_model_utils.py
* The attribute `self.steady_u` is set if `"fit_steady_u"` is a column in `adata.var`. Previously, it was checked if `"fit_steady_s"` is a column. The same is true the other way around, i.e. the attribute `steady_s` is set if `"fit_steady_s"` is a column in `adata.var`.
Closes #325.
=> Checked correct column name

scvelo/datasets.py
* Fixes `simulation` to work when specifying multiple noise levels and time switches but no number of variables.
Closes #327.
=> Fix simulation

.pre-commit-config.yaml, setup.py
* Bump version of `black` to `black==20.8b1`
* Use `black==20.8b1` in pre-commit hooks
Closes #343.
=> Fix developer installation

requirements.txt
* numba version is set to `>=0.41.0` (from scanpy) and `<0.53.0`.
Closes #387.
=> Pin numba version

scvelo/core/__init__.py, scvelo/core/_parallelize.py, scvelo/tools/dynamical_model.py
* The file `core/_parallelize.py` is added
* The functions `_parallelize` and `get_n_jobs` are moved to `core/`
* The function `_parallelize` is renamed to `parallelize`.
Related to #389.
=> Move parallelize machinery to core

scvelo/__init__.py, scvelo/core/__init__.py, scvelo/core/_anndata.py, scvelo/datasets.py, scvelo/preprocessing/neighbors.py, scvelo/preprocessing/utils.py, scvelo/read_load.py, scvelo/utils.py
Functions related to or performing operations on AnnData, are moved to `core/_anndata.py`.
* Functions moved from `preprocessing/utils.py`: `cleanup`, `get_initial_size`, `get_size`, `set_initial_size`, `show_proportions`, `verify_dtypes`. 
* Functions moved `read_load.py`: `clean_obs_names`, `get_df`, `merge`, `obs_df`, `var_df`.
Related to #389.
=> Move functions to core/_anndata.py

scvelo/core/_anndata.py
* Type hints are added to functions in `core/_anndata.py` which did not already include any.
* Docstrings are updated by removing explicit type specifications.
WIP towards closing/realizing #403.
=> Add type hints in core/_anndata.py

scvelo/core/_anndata.py
* Fix minor issues in docstrings (missing documentation, inconsistent argument names) in `clean_obs_names`, `get_df`, `merge` and `show_proportions`.
* Add docstrings to `get_initial_size`, `get_size`, `obs_df`, `set_initial_size`, `var_df` and `verify_dtypes`.
Contributing to #406.
=> Add and fix docstrings in core/_anndata.py

requirements.txt
* Allow versions `umap-learn>=0.5.0`.
Closes theislab/scanpy#1799.
=> Allow umap-learn>=0.5.0

scvelo/tools/dynamics/__init__.py, scvelo/tools/dynamics/_dynamics_base.py, scvelo/tools/dynamics/_recovery.py
* Adds submodule `dynamics`.
* Parameters of different models can be inferred by defining recovery classes. The classes inherit from `DynamiscRecoveryBase`. `SplicingDynamicsRecovery` has been implemented to recover the model parameters of the original 2D splicing model. The generalised dynamics recovery has been compared to the original implementation on simulated data. For this, the if clause [here](https://github.com/theislab/scvelo/blob/e77e01f09bba3e4c6e808ceda149563f47f3d134/scvelo/tools/dynamical_model.py#L270) was commented out and the default tolerance used [here](https://github.com/theislab/scvelo/blob/e77e01f09bba3e4c6e808ceda149563f47f3d134/scvelo/tools/dynamical_model.py#L184), [here](https://github.com/theislab/scvelo/blob/e77e01f09bba3e4c6e808ceda149563f47f3d134/scvelo/tools …
=> Generalized dynamics recovery

requirements.txt
* Adds `typing_extensions` to `requirements.txt`. This allows importing `Literal` in `python>=3.8`.
Closes #443.
=> Fix import of literal for Python>=3.8

scvelo/tools/dynamical_model.py
* Fix typo.
* Add explanation on how variable genes are determined if not yet defined through a column `velocity_genes` in `adata.var`.
Closes #497.
=> Update `recover_dynamics` docs

scvelo/core/_anndata.py
* Renames input arguments
* Uses Pandas functionality
* Uses regex expression to extract new observation names
* Renames variables to be more meaningful and be snake as well as lower case
Closes #531.
=> Refactor clean_obs_names

scvelo/core/__init__.py, scvelo/core/_arithmetic.py, scvelo/preprocessing/utils.py, tests/core/test_arithmetic.py
* `filter_genes` now works with `adata.layers['unspliced']` being sparse and `adata.layers['spliced']` dense.
* Adds function `multiply` for element-wise multiplication of arrays and sparse matrices
* Refactors `filter_genes` to make use of `multiply` and fix #533.
Closes #533.
=> Fix and refactor `filter_genes`

tests/core/test_base.py
* Adds option to add columns in `adata.obs` and `adata.var` when generating AnnData objects for testing.
* Extends and adds unit tests to test new feature.
* Updates and fixes docstrings to follow style of remaining code base.
Closes #543.
=> Add column generation for adata.obs and adata.var

tests/core/test_anndata.py, tests/core/test_base.py
* Adds method `_subset_columns` to `TestBase` to sample from `adata.obs` or `adata.var`.
* Adds `TestCleanup` with unit tests for `scvelo/core/_anndata.py::cleanup`.
Closes #547.
=> Add unit tests for cleanup

tests/core/test_anndata.py
* Fixes definition of columns to keep in `adata.var`.
Closes #549.
=> Fix TestCleanup::test_cleanup_some

scvelo/core/_anndata.py, tests/core/test_anndata.py
* Renames arguments of `cleanup`. `data` is superseded by `adata`, `copy` by `inplace`.
* Variable names in `cleanup` are updated to be more informative.
Closes #551.
=> Refactor `cleanup`

tests/core/test_anndata.py
* Adds test class `TestGetInitialSize` to unit test `get_initial_size`.
Closes #553.
=> Add `TestGetInitialSize`

scvelo/core/_anndata.py, tests/core/test_anndata.py
* Supports passing `None` for `modality` in `scvelo.core._anndata.py::get_modality`.
* Adds a unit test to `TestGetModality` to verify using `modality=None` returns correct data.
Closes #566.
=> Allow `None` as `modality` in `get_modality`

scvelo/core/_anndata.py, tests/core/test_anndata.py
* Renames argument `layer` to `modality`.
* Allows calculating counts per observation for an arbitrary modality, i.e. also from `adata.obsm`.
Closes #568.
=> Refactor and generalize `get_size`

tests/core/test_anndata.py
* Adds `TestObsDf` to unit test `scvelo.core._anndata.py::obs_df`.
Closes #578.
=> Add `TestObsDf`

scvelo/core/_anndata.py
* Fixes typo in default layer names in `scvelo.core._anndata.py::show_proportions` from `ambigious` to `ambiguous`.
Closes #586.
=> Fix typo in default layer names

tests/core/test_anndata.py
* Reduce maximum size to (5, 5) of generated AnnData objects in some tests.
Closes #592.
=> Reduce maximum number of obs/vars

tests/core/test_anndata.py
* Passes `layers=None` instead of specifying them explicitly in `TestShowProportions::test_layers_not_specified`.
Closes #597.
=> Fix TestShowProportions::test_layers_not_specified

tests/core/test_anndata.py
* Unit tests now also check correct behavior for different values of `inplace`.
Closes #599.
=> Extend `clean_obs_names` unit tests

tests/core/test_anndata.py
* Adds unit test `test_modalities_passed_as_string` to `TestMakeDense` and `TestMakeSparse` with `modality` passed as a string.
Closes #601.
=> Test modality passed as string

tests/core/test_anndata.py
* Generate layer names with at least two characters to exclude case `layer='X'`.
Closes #604.
=> Fix `TestGetInitialSize::test_not_existing_modality`

tests/core/test_metrics.py
* Converts unit test `test_l2_norm` to a test class `TestL2Norm`. 2D arrays and sparse matrices are now generated as well to increase coverage to 100%.
Closes #606.
=> Refactor `l2_norm` unit test

tests/core/test_anndata.py, tests/core/test_base.py
* Strategy `get_adata` can now also add entries to `adata.varm`.
* Unit tests in `TestAdataGeneration` are extended to include/test latest changes to `get_adata`.
Closes #608.
=> Add `varm` to AnnData strategy

scvelo/core/_models.py, tests/core/test_models.py
* Catch non-positive parameter values and raise `ValueError`
* Add unit test `TestSplicingDynamics.test_steady_state_not_defined` to raising of `ValueError`.
Closes #613.
=> Catch error in steady state calculation

scvelo/datasets/_simulate.py
* Fix `scvelo.datasets.simulation` using `noise_model="gillespie"`.
Closes #643.
=> Fix gillespie simulation

tests/datasets/test_datasets.py, tests/datasets/test_simulate.py
* Adds unit tests for `scvelo.datasets` in `tests.datasets.test_datasets.py` and `tests.datasets.test_simulate.py`.
Closes #645.
=> Add unit tests for `scvelo.datasets`

scvelo/preprocessing/utils.py, tests/preprocessing/test_utils.py
* Fixes calculation of Pearson's correlation in `csr_vcorrcoef`.
* Adds test class `TestCsrVcorrcoef`.
Closes #678.
=> Fix `csr_vcorrcoef`

.github/workflows/ci.yml
* Runs linting job in Python 3.8.
* Runs unit tests in 3.9 as well.
Related to #545.
=> Update Python versions in CI

scvelo/preprocessing/utils.py, scvelo/tools/rank_velocity_genes.py, tests/preprocessing/test_utils.py
* Makes `get_mean_var` work with sparse input and `ignore_zeros=True`.
* Update `get_mean_var` to use same size parameter for mean and variance.
* Fix `get_mean_var` s.t. passing `perc` works.
* Adds `TestGetMeanVar` to unit test `get_mean_var`.
Closes #695, #696, #697.
=> Fix and unit test `get_mean_var`

tests/core/test_anndata.py, tests/core/test_base.py
* Update strategy `get_adata` to exclude the key `"X"` in `.layers`, `.obsm`, `.varm`.
* Remove redundant statement in unit tests resulting from this update.
Closes #784.
=> Update AnnData generation for testing

.github/workflows/ci.yml, tests/datasets/test_datasets.py
* Ignore `tests/datasets/test_datasets.py` in `test` job of CI.
* Add job `test-dataset-downloads` to CI which only runs on `ubuntu-latest` and Python 3.8.
* Skip `test_datasets.py:TestDataSets` if Python version is not 3.8 and OS not Linux.
=> Speed up CI

scvelo/preprocessing/neighbors.py
* The variable `rep` was previously referenced before assignment if the if-else case was not entered.
* The warning statement is printed based on the value of `rep`.
Closes #796.
=> Fix `_get_rep`

.github/workflows/ci.yml, tests/conftest.py
* The deadline for tests using Hypothesis is set to 500 milliseconds.
Closes #803.
=> Increase Hypothesis deadline in CI

docs/source/getting_started.rst
If an `.h5ad` file can be generated directly by `kallisto`, this seems more straight forward than going through `loompy`. Why not point to this instead?
=> Recommend `kb count` instead of `loompy fromfq`

requirements.txt
* Prevents failure as reported in #811 
Closes #811.
=> Exclude `pandas==1.4`

scvelo/tools/optimization.py
* Fixes case where `perc` is numeric but not an integer which previously caused the `else` instead of `if` clause to be entered.
Closes #837.
=> Fix `optimization.py::get_weight`

scvelo/core/_anndata.py, tests/core/test_anndata.py
Switched implementation to use the previously ignored id_length
parameter. New approach finds a substring of length id_length
where each of the letters are in the alphabet
Resolves #843
=> Fix bug with clean_obs_names

scvelo/core/__init__.py, scvelo/core/_anndata.py, scvelo/core/_utils.py
* Add `core/_utils.py` with wrapper `deprecated_arg_names`.
* Use local wrapper `deprecated_arg_names` instead of Scanpy version.
Closes #931.
=> Fix deprecation of keyword argument `copy`

tests/preprocessing/test_neighbors.py
* Remove `TestNeighbors::test_duplicate_cells` to make tests pass. This is a temporary fix to make the CI pass. This unit test is not essential and the error is caused by numerical instability.
* Remove `TestNeighborsToBeRecomputed::test_without_pca_present`. This is a temporary fix to make the CI pass. This unit test is not essential and the error is caused by numerical instability.
* Remove `TestNeighborsToBeRecomputed::test_neighbors_recalculated`. This is a temporary fix to make the CI pass. This unit test is not essential and the error is caused by numerical instability.
Related to #922.
=> Remove non-essential unit tests from `test_neighbors.py`

.github/workflows/ci.yml
* Remove Python 3.7 from CI runs.
Closes #965.
=> Deprecate Python 3.7

docs/requirements.txt, requirements.txt, setup.py
- Remove `typing_extensions` dependency
- Update `setup.py` to require at least Python 3.8.
Artefacts from #965.
=> Deprecate Python 3.7 support

.readthedocs.yml
With moving the setup to toml, we need to point rtd to the requirements under `docs`
=> Point rtfd to docs requirements

scvelo/preprocessing/utils.py, tests/preprocessing/test_utils.py
Removes heuristic to determine if `adata.X` should be logarithmized or not.
* Removes heuristic to advise to logarithmize data or not
Closes #959.
=> Remove log advise heuristic in `preprocessing/utils.py::filter_and_normalize`

docs/source/_ext/edit_on_github.py
Set `stacklevel=2` in `warnings.warn`.
-   Specify stackelevel when calling `warnings.warn`
Closes #1019.
=> Add stacklevel to `warnings.warn`

scvelo/tools/_em_model_core.py
* Modifies the way parameters are set in `scv.tl.recover_dynamics`
Closes #1058
=> Fix tl.recover_dynamics

scvelo/preprocessing/utils.py, tests/preprocessing/test_utils.py
-   Deprecates `log1p` in favor of Scanpy's implementation
Closes #1066.
=> Deprecate `log1p`

scvelo/tools/_em_model_core.py
This fixes a bug in `scv.tl.rank_dynamical_genes` where an attempt to slice a pandas index using a multidimensional numpy array raises a `ValueError` as that type of operation is no longer supported.  Now, the pandas index is cast to a numpy array prior to slicing.
Closes #1087
=> FIX: scv.tl.rank_dynamical_genes and multidimensional array

scvelo/tools/_em_model.py, tests/test_basic.py
- Class `EMParams` is now used by the `ExpectationMaximizationModel` in `tools/_em_model.py`.
Closes #1026, #1025.
=> Add usage of `EMParams`

.github/workflows/release.yml
Adds CI jobs to create new releases.
@WeilerP 2 things need to be done:
Closes #1146.
=> Add release GitHub action

.github/workflows/build.yml, .github/workflows/ci.yml, CONTRIBUTING.rst, README.md, debug.py, docs/source/_ext/edit_on_github.py, docs/source/conf.py, docs/source/index.rst, scvelo/datasets/_read.py
-   Renames scvelo's `master` branch to `main`
- Removes redundant branches in CI workflow
Closes #1153.
=> Update branch names

.github/workflows/ci.yml, pyproject.toml, scvelo/tools/__init__.py, scvelo/tools/_core.py, scvelo/tools/_vi_module.py, tests/tools/test_vi_model.py
Make `scvi-tools` install optional as `pip install 'scvelo[vi]'`.
Related to the failing CI, see here: https://github.com/theislab/cellrank/pull/1156#issuecomment-1932823547
Closes #1189.
=> Remove hard `scvi-tools` dependency

scvelo/plotting/scatter.py, scvelo/plotting/utils.py
- Add keyword `aspect` to set axis aspect.
Closes #1204.
=> Update `scatter` and `update_axes`

scvelo/tools/_em_model_core.py, scvelo/tools/velocity_graph.py
- Add arguments to make progress bar optional for parallelization
Related to #1128.
=> Make progress bar optional

scvelo/inference/_metabolic_labeling.py
- Use `items` instead of `iteritems`.
Closes #1261.
=> Fix iteration over Pandas Series

scvelo/core/_anndata.py, scvelo/core/_linear_models.py, scvelo/inference/_metabolic_labeling.py, scvelo/plotting/heatmap.py, scvelo/plotting/utils.py, scvelo/plotting/velocity.py, scvelo/plotting/velocity_graph.py, scvelo/preprocessing/moments.py, scvelo/preprocessing/neighbors.py, scvelo/tools/optimization.py, scvelo/tools/paga.py, scvelo/tools/run.py, scvelo/tools/terminal_states.py, scvelo/tools/transition_matrix.py, scvelo/tools/utils.py, scvelo/tools/velocity_embedding.py, scvelo/tools/velocity_graph.py, tests/core/test_anndata.py, tests/preprocessing/test_moments.py, tests/preprocessing/test_neighbors.py, tests/preprocessing/test_utils.py
- Switch from `.A` to `.toarray()`
Closes #1260
=> Update densifying sparse array

pyproject.toml
- Unpins upper version of numpy.
=> Remove numpy<2.0.0 pin
